name: CD 

on: 
  push:
    branches: ["main"]

jobs:
  deploy:
    name: deploy
    # runs-on -> specifies type of runner to use
    runs-on: ubuntu-latest

    # job steps
    steps:
      - name: Set up Go
        # uses -> action to use 
        uses: actions/setup-go@v4
        # with -> input to the action 
        with:
          go-version: "1.20"
          
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build the app 
        run: ./scripts/buildprod.sh
