# workflow name -> human-readable name to the workflow
name: ci 

# Triggering the workflow
# on -> key specifies when the workflow should run
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

# jobs -> key is a list of jobs that make up the workflow
jobs:
  # first job -> tests
  tests:
    # name -> key assigns a human-readable name to the job 
    name: tests
    # runs-on -> specifies type of runner to use
    runs-on: ubuntu-latest

    # job steps
    steps:
      - name: Set up Go
        # uses -> action to use 
        uses: actions/setup-go@v4
        # with -> input to the action 
        with:
          go-version: "1.20"
          
      - name: Check out code
        uses: actions/checkout@v3

      - name: Formatting CI
        run: go fmt ./...

      - name: test formatting 
        run: test -z $(go fmt ./...)

      - name: install staticcheck 
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: staticcheck 
        run: staticcheck ./...
